server:
  port: 7788
spring:
  application:
    name: dome01
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds1
      ds1:
        # 配置druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        drive-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/order_db?useUnicode=true
        username: root
        password: 123456
#    sharding:
#      tables: 
#        t_order:
#          actual-data-nodes: m1.t_order_$->{1..2}
#          key-generator:
#            column: order_id
#            type: SNOWFLAKE
#          table-strategy:
#            inline:
#              sharding-column: order_id
#              algorithm-expression: t_order_$->{order_id % 2 + 1}
#    props: 
#      sql:
#        show: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.domain
